### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by H401217** [DaniElectra/PouClients#1]
# [Online Connection](https://github.com/DaniElectra/PouClients/wiki/Online-connection-(Overview)#parameters)
* "_a" serves as indicator that you're accessing an API, if this value isn't set then some endpoints would return an HTML value.
# [Registering](https://github.com/DaniElectra/PouClients/wiki/Online-connection-(Authentication)#register)
* CAPTCHA base64 (unescaping the "\\") doesn't work, unless you remove the 11th character.
# [Game Sessions](https://github.com/DaniElectra/PouClients/wiki/Online-game-sessions)
* The game session can be modified in an irregular way, creating invalid objects and strings in the match. Hopefully Pou has a way to prevent crashing when reading an invalid match.
# [Sending Messages](https://github.com/DaniElectra/PouClients/wiki/User-endpoint#post-usersend_message)
* You can only send 1 message of each type. If you send the message twice, instead of getting duplicated it will be reordered to be the most recent message.
# Other suggestions
* The "state" object returned by some endpoints can be JSONfied recursively if your code can do that.
  * Also that object can be a broken object, for example I found some player's JSON that had strings without quotes.

**Comment by H401217** [comment]
Postdata: You can search **banned users** using the "search/friend_by_nickname", "search/friend_by_email" and "search/random_friend" endpoints

**Comment by DaniElectra** [comment]
> The game session can be modified in an irregular way, creating invalid objects and strings in the match. Hopefully Pou has a way to prevent crashing when reading an invalid match.

Luckily the Pou code has many `try {} catch {}` error handling on it, although many of them don't actually handle the error and just doesn't do anything with it. This is an example of pseudo-code for the handler on Pou vs Pou:

![imagen](https://github.com/DaniElectra/PouClients/assets/112760654/aee0c17c-0b1a-4dfa-8255-f9b6c2ac8d50)

I wonder if there is somewhere where error handling is missing...

**Comment by H401217** [comment]
> > The game session can be modified in an irregular way, creating invalid objects and strings in the match. Hopefully Pou has a way to prevent crashing when reading an invalid match.
> 
> Luckily the Pou code has many `try {} catch {}` error handling on it, although many of them don't actually handle the error and just doesn't do anything with it. This is an example of pseudo-code for the handler on Pou vs Pou:
> 
> ![imagen](https://user-images.githubusercontent.com/112760654/260551727-aee0c17c-0b1a-4dfa-8255-f9b6c2ac8d50.png)
> 
> I wonder if there is somewhere where error handling is missing...

I discovered about corrupt game sessions while trying to create a tictacpou bot. I tried to open a corrupt game session and it just showed an android toast (a small messsage in bottom of screen) that said that an error has occurred

**Comment by H401217** [comment]
About "High Graphics" in Pou:
**Probably** Pou app draws all things in a canvas and then it draws the entire canvas to the screen only when "High Graphics" option is disabled. And Pou app probably draws all things directly to screen when that option is enabled.

How?
When enabling "debug GPU overdraw" in developer options from android and opening Pou app you can see that nothing changed (when "High Graphics" option is disabled) or you can see colored squares (when "High Graphics" option is enabled") that indicate the state of the overdraw. [There is a page about GPU overdraw](https://developer.android.com/topic/performance/rendering/inspect-gpu-rendering#debug_overdraw)
Also, Pou app automatically disables "High Graphics" option when it crashes.

**Comment by H401217** [comment]
"_r" value was changed in recent update 1.4.114
Value got changed to "263" (package version code)
Edit: some smali folders changed position from "classes" to "classes2" like for example "me.pou.app" and network scripts (from "classes/k5" to "classes2/n6")

**Comment by DaniElectra** [comment]
Thanks for keeping me updated on this! With the recent announcement of the shutdown of Nintendo Network, my main focus is on [Pretendo](https://github.com/PretendoNetwork), so I didn't have time to look on this

> Edit: some smali folders changed position from "classes" to "classes2" like for example "me.pou.app" and network scripts (from "classes/k5" to "classes2/n6")

That's interesting. I can still interact with the API when using the old revision number. Do you know if something has been updated on the network scripts aside from the revision?

**Comment by H401217** [comment]
I use winmerge to see the changes in folders and it's a bit complicated to see the changes between the scripts because the major change are the dependencies (because folders changed position)

Old revisions are still compatible because App Store Pou is still stuck in version 1.4.107

**Comment by H401217** [comment]
**update: classes got updated again
"classes2/n6" (internet) changed to "classes/s6"**

about the notifications (notifiactions/claim) i think you can use it to award coins and objects(maybe?) i did a bit of research months ago but forgot to post

a notification json can contain the following values
"i" --notification ID
"t" --type? (between coins and other stuff)
"oT" --object Type? (clothing?)
"oI" --object Id?
"a" --
"u2I" --???
"o2I" --???

a notification with type "33" will allow to award coins using the "a" value
```json
{"i":666,"t":33,"a":1234567890} //this gives 1234567890 coins
```

idk if this changed in 1.4.118 (new update)

[i also made some pou vs pou documentation (i will probably add more if possible)](https://h401217.github.io/docs/pvp.html)

**Comment by DaniElectra** [comment]
@H401217 Thanks for reaching out once again! I was thinking about something, maybe we could create an organization or something where we could both push code to a shared repo with documentation about the Pou API and Pou vs Pou? That way we wouldn't have to duplicate documentation on our repos. We could also have our code tests like this repo `PouClients` or your [Pou rigging example](https://h401217.github.io/pourig.html) on there

What are your thoughts? If you agree, I'll be fine with whatever name you choose for the org/repo. If you don't, then you're all good, and we can continue like everything is currently right now.

If you want to discuss some more details about this, I'm on Discord under the same username (danielectra). Feel free to reach out!
